# Description: Docker compose file for a Node.js app with MongoDB at production
# Author: Sebastián Gámez Ariza

version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
