# Description: Dockerfile to deploy the node application with hot reload at development
# Author: Sebastián Gámez Ariza

FROM node:16.19.1

RUN mkdir /home/app

WORKDIR /home/app

EXPOSE 3000

CMD ["npm", "run", "dev"]